# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Kursevi"
#  url = "#about"
#  weight = 10

[[main]]
  name = "Kursevi"
  url = "courses/"
  weight = 20


[[courses]]
  name = "Kursevi"
  weight = 10
  url = "/courses/"

[[courses]]
  name = "Osnove demografije"
  weight = 20
  identifier = "OD"


[[menu.OD]]
  name = "OD"
  weight = 20
  url = "/courses/OD/"


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
